### ISSUE TITLE
Provide aarch64 cache :grimacing: 

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/nix-thunk#15]
Building GHC from source to get nix-thunk is a bit...extreme.

**Comment by 3noch** [comment]
This could possibly be solved by just doing #14

**Comment by develop7** [comment]
I wonder why the cache is still not up, especially since it's apparently cheap, isn't it?

**Comment by develop7** [comment]
> On x86: Building from source takes a while.

5 minutes is a while. 20 and counting on a single CPU (with other 23 idling) is, um, huge.

**Comment by ali-abrar** [comment]
#72
